Fix typos in RU-ru translation.
ShankarBUS/ModernFlyouts pull request #235
Opened 2020-11-20 12:55 UTC by blinchk

Started to use ur's application and found some typos in Russian translation.
I want to offer u my corrections for it.

2020-11-21 13:08 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Современные флайауты</target>
Это название программы. Лучше оставить оригинал "ModernFlyouts"

2020-11-21 13:57 UTC, ANT0x1 requested changes
Minor fixes.
Will fix more after merge.

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="tm-suggestion">Запускать при загрузке системы</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="tm-suggestion">Автозагрузка</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Современные флайауты</target>
Это название приложения. Лучше оставить оригинал.
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">ModernFlyouts</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Данное приложение предназначено для замены старых всплывающих окон стиля Metro на современные окна современного стил
Тавтология, не находишь?) Дословно переводить не имеет смысла.
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Данное приложение разработано для замены старых всплывающих окон, присутствующих в Windows со времен Windows 8, на современные.</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Если вы обнаружите какие-либо ошибки, пожалуйста, откройте новую проблему в репозитории на GitHub.</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Если вы обнаружите какие-либо ошибки, пожалуйста, сообщите о них в репозитории на GitHub.</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Показывать GSMTC (всплывающие окна медиа)</target>
Не совсем очевидно. Опция предназначена для отображения контролов на всплывающей панели.
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Отображать элементы управления медиа на панели громкости</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
>            <source>Scroll lock</source>
Это тоже бы оставить как есть. "Блокировка прокрутки" вводит в ступор обычного пользователя.

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить всплывающие окна режима полёта</target>
Будет лучше "Включить модуль" либо же просто "Активировать".
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить модуль</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить всплывающие окна аудио</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить модуль</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить всплывающее окно яркости</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить модуль</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить всплывающее окно клавиш блокировки</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Включить модуль</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Отображать иконку в трее системы</target>
Кроме иконок в трей как бы ничего и не засунешь.
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Отображать в трее</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Современные всплывающие окна</value>
Название программы.
```suggestion
    <value>ModernFlyouts</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Выберите всплывающих окон по умолчанию.</value>
```suggestion
    <value>Выберите стиль</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Непрозрачность фона всплывающих окон.</value>
```suggestion
    <value>Непрозрачность всплывающего окна</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Позиция всплюыващих окон по умолчанию (для кнопки сброса выравнивания)</value>
```suggestion
    <value>Положение всплывающего окна по умолчанию (для кнопки сброса выравнивания)</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Модуль "Режим полёта"</value>
```suggestion
    <value>Режим полёта</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Верхняя панель всплывающих окон</value>
По контексту и так понятно, что речь о всплывающих окнах.
```suggestion
    <value>Верхняя панель</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
>      <value>Модуль "Аудио"</value>
```suggestion
    <value>Медиа</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
>      <value>Модуль "Яркость"</value>
```suggestion
    <value>Яркость</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Модуль "Клавиши блокировки (Num Lock и т.д.)"</value>
Нет смысла в длинном тексте, т.к. в меню все равно будет видна небольшая часть.
```suggestion
    <value>Клавиши блокировки</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Запускать при загрузке системы</value>
```suggestion
    <value>Автозагрузка</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Задержка всплывающего окна (мс)</value>
Время, на которое будет показано окно.
```suggestion
    <value>Время отображения всплывающего окна (мс)</value>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
>            <target state="needs-review-translation" state-qualifier="mt-suggestion">Количество сеансов для показов</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Количество отображаемых сеансов</target>
```

2020-11-21 13:57 UTC, ANT0x1 commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Тайм-аут всплывающего окна (в мс)</target>
```suggestion
          <target state="needs-review-translation" state-qualifier="mt-suggestion">Время отображения (мс)</target>
```

2020-11-21 14:06 UTC, blinchk commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
> +          <target state="needs-review-translation" state-qualifier="mt-suggestion">Данное приложение предназначено для замены старых всплывающих окон стиля Metro на современные окна современного стил
Update About.AppDescription translation at ModernFlyouts.ru.xlf

2020-11-21 14:08 UTC, blinchk commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Модуль "Клавиши блокировки (Num Lock и т.д.)"</value>
Тогда было бы правильно переименовать и остальные пункты меню для того, чтобы оно выглядело едино.

2020-11-21 14:08 UTC, blinchk commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Модуль "Клавиши блокировки (Num Lock и т.д.)"</value>
![image](https://user-images.githubusercontent.com/49353043/99879189-2bc57780-2c1c-11eb-81d0-8a13255bda17.png)

2020-11-21 14:18 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.ru.resx
> +    <value>Модуль "Клавиши блокировки (Num Lock и т.д.)"</value>
Согласен.
Убрать слова "Модуль" и оставить лишь их названия.

2020-11-21 14:25 UTC, blinchk commented on ModernFlyouts/MultilingualResources/ModernFlyouts.ru.xlf
>            <source>Scroll lock</source>
```suggestion
          <source>Scroll Lock</source>
```

2020-11-21 14:27 UTC, ANT0x1 approved these changes

2020-11-21 14:46 UTC, ShankarBUS commented
Is it ready to merge?

2020-11-21 14:56 UTC, ANT0x1 commented
@ShankarBUS yup

2020-11-21 15:00 UTC, ShankarBUS commented
@Samuel12321, don't forgot to include @ANR0x1 as the Co-Author in the commit message.

Seems like @blinchk and @ANT0x1 collaborated to fix the translations.

If you don't know how to add co-authors to commits, then I will merge this PR myself.

Great work guys!
Thanks for helping us out!

2020-11-22 02:01 UTC, Samuel12321 approved these changes
Thanks so much @blinchk and @ANT0x1 ,
looks great. 
Will be visible in the next release (0.8.5)

2020-11-22 02:01 UTC, merged