Update uk-UA translation
ShankarBUS/ModernFlyouts pull request #247
Opened 2020-11-23 18:30 UTC by Tarik02

2020-11-24 13:39 UTC, ANT0x1 requested changes

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Панель режиму "У літаку"</value>
У назвах модулей дублювати "панель" не має сенсу, бо в меню вже є цей напис.

```suggestion
    <value>У літаку</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Панель аудіо</value>
```suggestion
    <value>Аудіо</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Панель яскравості</value>
```suggestion
    <value>Яскравість</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Панель перемикачів</value>
```suggestion
    <value>Перемикачі</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Запускати разом з Windows</value>
```suggestion
    <value>Автозавантаження</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Сучасні панелі</value>
Назва застосунку.
```suggestion
    <value>ModernFlyouts</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Ця програма розроблена для замыни старих метро-панелей , присунтіх у Windows починаючи з Windows 8, на нові в стилі Fluent Design.</value>
```suggestion
    <value>Ця програма розроблена для заміни старих метро-панелей, присунтіх у Windows починаючи з Windows 8, на нові в стилі Fluent Design.</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Відкриття нового Issue</value>
```suggestion
    <value>Повідомити про проблему</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Оцінити та переглянути у Магазині Microsoft</value>
```suggestion
    <value>Оцінити у Microsoft Store</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Якщо ви знайшли якісь помилки, будь ласка, відкрийте новий issue у репозиторії на GitHub.</value>
```suggestion
    <value>Якщо ви знайшли якісь помилки, будь ласка, повідомте про них в репозиторії на GitHub.</value>
```

2020-11-24 13:39 UTC, ANT0x1 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Показати глобальні елементи керування медіатранспортом (GSMTC) aka Media у панелі гучності</value>
```suggestion
    <value>Відображати елементи керування медіа на панелі гучності</value>
```

2020-11-24 13:58 UTC, Tarik02 commented on ModernFlyouts/Properties/Strings.uk.resx
> +    <value>Панель режиму "У літаку"</value>
О, дякую) маєте рацію.

2020-11-24 14:47 UTC, ANT0x1 approved these changes

2020-11-28 08:40 UTC, Samuel12321 approved these changes
Looks good thanks.

2020-11-28 08:40 UTC, merged